[package]
name = "haxrs"
version = "0.1.0"
edition = "2021"
authors = ["skyline"]
license = "MIT"
description = "Hax is a mini-tool with really useful hacking tools."
repository = "https://github.com/skyline69/HaxRS"
readme = "README.md"
homepage = "https://skyline69.live"
categories = ["hacking", "tools", "cli"]
keywords = ["hacking", "tools", "cli"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clearscreen = { version = "2.0.1", features = ["windows-console"] }
colored = "2.0.0"
ping = "0.4.1"
reqwest = { version = "0.11.17", features = ["json", "blocking"] }
serde_json = "1.0.96"
socket2 = "0.5.2"
tokio = { version =  "1.28.0", features = ["full"] }

[profile.release]
opt-level = 3
debug-assertions = false
overflow-checks = false
lto = true
debug = false
